version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411

  mongo:
    container_name: mongo
    networks:
      - shared-network
    image: mongo:4.4.5
    ports:
      - 27017:27017      

  drop-api:
    container_name: drop-api
    networks:
      - shared-network
    image: drop-api-amd64:1.0
    ports:
      - 3000:3000 # CRUD API
      - 4000:4000 # DEBUG API
    depends_on:
      - zipkin
      - mongo

  metrics:
    container_name: metrics
    networks:
      - shared-network
    image: metrics-amd64:1.0
    ports:
      - 3001:3001 # EXPVAR API
      - 4001:4001 # DEBUG API
    depends_on:
      - drop-api